spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wust_basic?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.linghang.backend.mywust_basic.Dao
logging:
  file:
    name: D:\\log\\mywustBasic.log
jwt:
  secret: ""
  expiration:
aes:
  secret: ""
WustHelper:
  term: ""
